services:
  backend:
    image: backend-app:latest
    container_name: backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - shared_data:/app/shared

  frontend:
    image: frontend-app:latest
    container_name: frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      # - certbot
      - backend
      - frontend
    networks:
    - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  app-network:
    driver: bridge

volumes:
  shared_data:

